n = int(input('Digite um número inteiro: '))
print('-'*18)
print(f'A tabuada do {n} é:')
print(f'{n:2}*1 = {n * 1}')
print(f'{n:2}*2 = {n * 2}')
print(f'{n:2}*3 = {n * 3}')
print(f'{n:2}*4 = {n * 4}')
print(f'{n:2}*5 = {n * 5}')
print(f'{n:2}*6 = {n * 6}')
print(f'{n:2}*7 = {n * 7}')
print(f'{n:2}*8 = {n * 8}')
print(f'{n:2}*9 = {n * 9}')
print(f'{n:2}*10 = {n * 10}')
print('-'*13)